### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by zaneobrien** [zaneobrien/game-checkout-frontend#1]
Test

**Comment by alexlouden29** [comment]
Is it just comments, no dedicated description section?  I can edit your comment, so I guess the first comment can always be the description, just kind of odd.  Otherwise, lightweight, good enough for what we're doing.

**Comment by zaneobrien** [comment]
Yea, I think its just the first comment is supposed to describe the issue

**Comment by tletuan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scaffold Angular 5 or 6 Client](https://trello.com/c/2W0SXtXo/1-scaffold-angular-5-or-6-client)

**Comment by tletuan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scaffold Sring Boot Application](https://trello.com/c/LSmyEago/2-scaffold-sring-boot-application)
